# Server configuration
server.port=8085

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/udhr_db
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Security Configuration
jwt.secret=udhr-secret-key-2026-university-mpumalanga
jwt.expiration=86400000
